# Do not add any sensitive configuration values here, e.g. access keys or passwords.
# any sensitive config KEYS should be added to .env.example for reference and validation
# and to your personal .env file (ignored in vcs), keys which are present in .env.example and not in .env
# will cause the application to throw an exception with the missing variable.
default:
  cache-max-age: 5
  cors:
    # Additional headers to add to Access-Control-Allow-Headers header.
    allowHeaders:
#      - 'X-My-Custom-Header'

# Test environment is used for running tests.
test:
  mongo:
    url: 'mongodb://fake.co:27017/'
    collection: 'Example-Service'

# i.e. development.
development:
  mongo:
    url: 'mongodb://localhost:27017/'
    collection: 'Example-Service'

# i.e. staging.
staging:
  mongo:
    url: 'mongodb://stg-mongo.playbuzz.local:27017/'
    collection: 'Example-Service'

# Production.
production:
  mongo:
    url: 'mongodb://mongo.playbuzz.local:27017/'
    collection: 'Example-Service'
